Frontends/TechnoMarket.Web/Models/Basket/BasketItemVM.cs
namespace TechnoMarket.Web.Models.Basket
{
    public class BasketItemVM
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; } = 1;
        public decimal Price { get; set; }
    }
}

Frontends/TechnoMarket.Web/Models/Basket/BasketVM.cs
namespace TechnoMarket.Web.Models.Basket
{
    public class BasketVM
    {
        public BasketVM()
        {
            BasketItems = new List<BasketItemVM>();
        }

        public string UserId { get; set; }
        public List<BasketItemVM> BasketItems { get; set; }
        public decimal TotalPrice
        {
            get => BasketItems.Sum(x => x.Price * x.Quantity);
        }
    }
}

Frontends/TechnoMarket.Web/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TechnoMarket.Web.Models.Basket;
using TechnoMarket.Web.Services.Interfaces;

namespace TechnoMarket.Web.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly ICatalogService _catalogService;
        private readonly UserManager<IdentityUser> _userManager;

        public BasketController(IBasketService basketService, ICatalogService catalogService, UserManager<IdentityUser> userManager)
        {
            _basketService = basketService;
            _catalogService = catalogService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var basketVM = await _basketService.GetAsync(user.Id);

            return View(basketVM);
        }

        public async Task<IActionResult> AddBasketItem(string productId)
        {
            var product = await _catalogService.GetProductByIdAsync(productId);

            var basketItemVM = new BasketItemVM
            {
                ProductId = product.Id,
                Price = product.Price,
                ProductName = product.Name
            };

            var user = await _userManager.GetUserAsync(User);

            await _basketService.AddBasketItemAsycn(basketItemVM, user.Id);

            return RedirectToAction(nameof(Index), "Home");
        }

        public async Task<IActionResult> RemoveBasketItem(string productId)
        {
            var user = await _userManager.GetUserAsync(User);

            await _basketService.RemoveBasketItemAsycn(productId, user.Id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Frontends/TechnoMarket.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TechnoMarket.Web.Models.Order;
using TechnoMarket.Web.Services.Interfaces;

namespace TechnoMarket.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IBasketService _basketService;
        private readonly ICustomerService _customerService;
        private readonly UserManager<IdentityUser> _userManager;

        public OrderController(IOrderService orderService, IBasketService basketService, ICustomerService customerService, UserManager<IdentityUser> userManager)
        {
            _orderService = orderService;
            _basketService = basketService;
            _customerService = customerService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.GetUserAsync(User);

            var basket = await _basketService.GetAsync(user.Id);

            ViewBag.Basket = basket;

            return View(new CheckoutInput());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutInput checkoutInput)
        {
            var user = await _userManager.GetUserAsync(User);

            var customerVM = await _customerService.GetCustomerByEmailAsync(user.Email);

            if (customerVM == null)
            {
                customerVM = await _customerService.CreateOrder(checkoutInput);
            }

            #region Senkron Yol
            //Senkron yol
            //var order=await _orderService.CreateOrderAsync(checkoutInput, customerVM.Id, user.Id); 
            #endregion

            //Asenkron yol
            var orderSuccess = await _basketService.CheckOutForAsyncCommunication(checkoutInput, customerVM.Id, user.Id);

            if (!orderSuccess)
            {
                return RedirectToAction("ErrorPage", "Home");
            }

            await _basketService.DeleteAsycn(user.Id);
            return RedirectToAction(nameof(CheckoutHistory));
        }

        public IActionResult CheckoutHistory()
        {
            return View();
        }

    }
}

Frontends/TechnoMarket.Web/Views/Basket/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model BasketVM

<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Basket</h5>

                @if (Model != null && Model.BasketItems.Any())
                {
                    <table class="table table-striped">
                        <tr>
                            <th>Product Name</th>
                            <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Action</th>
                        </tr>

                        @foreach (var item in Model.BasketItems)
                        {
                            <tr>
                                <td>@item.ProductName</td>
                                <td>@item.Price $</td>
                                <td>@item.Quantity</td>
                                <td>
                                    <a asp-controller="Basket" asp-action="RemoveBasketItem" asp-route-productId="@item.ProductId" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }

                        <tr>
                            <th colspan="4">Total Price: @Model.TotalPrice $</th>
                        </tr>
                    </table>

                    <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Payment Details</a>
                    <a class="btn btn-warning" asp-controller="Home" asp-action="Index">To continue reviewing courses</a>

                }
                else
                {
                    <div class="alert alert-info">Basket is empty!</div>
                }
            </div>
        </div>
    </div>
</div>